### ISSUE TITLE
lockbot gets stuck on a locked resource if the string contains backticks

### ISSUE THREAD

**Issue by MattPalladino** [connorads/lockbot#161]
Hi everyone, 

I've encountered a bug that results in a resource being stuck in the locked state. When writing the following command:

```
/lock `resource-name`
```

which resulted in the locking of ` ``resource-name`` `, which now cannot be unlocked, since when trying to `/unlock` it, the string is shown without the double backtics (and it's obviously not equal to the string with the backtics).

This is not too serious, just an inconvenience since it pollutes the locked resource list, but still it would be useful to make sure to sanitize the input to avoid any kind of formatting error resulting in erroneous resources being locked.

Thanks for the attention!

**Comment by connorads** [comment]
Hey @MattPalladino,

You should be able to unlock it by unlocking exactly what you locked.

i.e.
```unlock `some-resource`
```

Example:
![Screenshot_20220512-005101~2.png](https://user-images.githubusercontent.com/10026538/167960415-3d2673f3-c041-472f-907a-b873ee82b4fc.png)
