### ISSUE TITLE
Add to slack button not working

### ISSUE THREAD

**Issue by ahenestrosa** [connorads/lockbot#175]
The button used to 'Add to slack' in the main page is not working as Jan 23, 2023.

**Comment by connorads** [comment]
Thanks for reporting, should be working now 🤞 
https://lockbot.app/

**Comment by andrewfrankel** [comment]
@connorads broken again...

<img width="658" alt="Screenshot 2023-01-27 at 6 17 17 AM" src="https://user-images.githubusercontent.com/1470345/215096239-1ef3723e-f159-40e8-b0d0-851f19a066ee.png">

<img width="718" alt="Screenshot 2023-01-27 at 6 17 22 AM" src="https://user-images.githubusercontent.com/1470345/215096241-88311c08-ff5f-4d3d-afdd-d73252b53fb2.png">

**Comment by connorads** [comment]
Thanks @andrewfrankel, taking a quick look now

**Comment by connorads** [comment]
It's back up now @andrewfrankel

![Screen Shot 2023-01-27 at 1 33 51 PM](https://user-images.githubusercontent.com/10026538/215099341-bb1384ef-60d3-4ce3-b150-724d43dbb028.png)
![image](https://user-images.githubusercontent.com/10026538/215099369-c612c303-b196-4e7f-a3a8-99932dd7908f.png)

**Comment by andrewfrankel** [comment]
Thanks for the quick turnaround, works again!
