### ISSUE TITLE
Feature: show the time a resource was locked in the slack message

### ISSUE THREAD

**Issue by RaniSputnik** [connorads/lockbot#80]
When I run the `/locks` command in Slack I would love to see what time each resource was locked.

<img width="375" alt="Screenshot 2021-02-05 at 09 55 01" src="https://user-images.githubusercontent.com/4233139/107018340-395cb900-6798-11eb-9e1e-7ef051c5e64c.png">

The reason I want this is I want an easier way to tell whether a lock is stale (and someone's forgotten to clean it up) or if it's been recently locked. Other features requested include notifications and I'd prefer that setup too! But this seemed like an easier improvement so thought I'd suggest it here too 😉

**Comment by connorads** [comment]
Nice idea @RaniSputnik
